steps:


# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/constellation-275522/vmproject:latest'
  - './vmProjectBackend'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/constellation-275522/vmproject:latest'

# This step deploys the dev application in Kubernetes
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=dev.yaml
  - --image=gcr.io/constellation-275522/vmproject:latest
  - --location=us-east1-b
  - --output=/tmp/outputdev
  - --cluster=cluster-1  

# This step runs the ConstellationTests Image 
# The PROJECT_ID variable is automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: run
  env:
  - 'NODE_ENV=development'
  args:
  - 'run'
  - 'gcr.io/constellation-275522/vmproject:latest'
  - 'npm'
  - 'run'
  - 'test-dev'

