steps:
# This step builds the container image.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/constellation-275522/vmprojectapiv2:latest'
      - './'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/constellation-275522/vmprojectapiv2:latest'

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=test.yaml
      - --image=gcr.io/constellation-275522/vmproject:latest
      - --location=us-east1-b
      - --output=/tmp/outputdev
      - --cluster=cluster-1  

timeout: 3600s
